### PR TITLE
complate BT / BLE communicity

### PR DESCRIPTION
**Pull request by yuht**
WARING : please test.
1.replace "\r" with "\r\n"
2.add pan_cmd_disable_uart_rtscts_control
3.add some command tu complate BT communicity
    pan_cmd_le_mng_ssp_set_req1 
    pan_cmd_le_mng_ssp_set_req2
    pan_cmd_le_mng_ssp_set_req3
    pan_cmd_le_mng_ssp_set_req4
    pan_cmd_le_mng_ssp_set_req5
4..add "#ifdef DEBUG_BT_ENABLED" to block function "for" in some zone have mor "DEBUG_BT"

### CODE REVIEW

**Comment by fhorinek** [comment]
Hi yuht,

Thank you for contributing.

1.replace "\r" with "\r\n"
This is not necessary since almost every terminal can break line on \n, please revert this change.

What exactly do commands pan_cmd_le_mng_ssp_set_req* do, can you point me to the documentation?

Also the numbering in enum serves as fast reference for debugging, I would like to keep it.

**Comment by yuht** [comment]
1.Microsoft  Widows ,"\r\n" means the new line . "\r" not means new line.
2.In other bluedevice ,had tc35661 bt chip. I found this " `pan_cmd_le_mng_ssp_set_req`*" commands.
in your code now, if without " `pan_cmd_le_mng_ssp_set_req`* " ,my device' bt not support BLE, so ,device can not pair wiht BT. 
You can TEST those code for confirmation.

3.btw, DEBUG_BT , if those code like this
//-------------------------------------
```
for( uint8_t i=0 ;i <100,i++)
     DEBUG_BT(....................);
//-------------------------------------
```
if DISABLE DEBUG_BT .code was change
//---------------------------------------
```
for( uint8_t i=0 ;i <100,i++)
     ;
```
//---------------------------------------
why lift  EMPTY  "`for( uint8_t i=0 ;i <100,i++)`"? 


thank you for your attention.

**Comment by fhorinek** [comment]
1. **\r** means carriage return. I am using **\n** which means new line. **\r\n** means carriage return and new line, but we are not using teleprinters anymore. I know that windows is still using this ancient method, but it is not relevant since you can choose how to interpret this character in serial terminal. DEBUG(...) macro is used send debug messages over the serial line. So please revert it.

2. I will try it with my hardware

3. This is true but it is not really needed since code like 
```
for( uint8_t i=0 ;i <100,i++)
     ;
```
will be dropped by GCC compiler anyway

BTW. Who are you? What is your goal? I do not think that you are paraglider :). Anyway thank you for you contribution.

**Comment by yuht** [comment]
tkank you!
fhorinek!
I am use TC35661-501 module. On github I am found your project.
keep SOURCE CODE FILE CLEANER  and  let seems well is not the compiler's work. Its by writer.

Those command you test and conf, I think its useful.

**Comment by yuht** [comment]
I'm not paraglider. I'm just use TC35661-501 chip.

**Comment by yuht** [comment]
those code let phone that its had BT but not support BLE.

**Pull request closed without merging**
