### PR TITLE
New widgets "odometer", "Home Arrow" and "Home Distance"

### PR DESCRIPTION
**Pull request by bubeck**
"odometer" gives the number of km/mi travelled.
"Home Arrow" is an arrow showing the direction from where we started. This is useful to find back (paramotor)
"Home Distance" is the distance from where we started. This is useful to find back (paramotor).

Fixes
https://github.com/fhorinek/SkyDrop/issues/184
https://github.com/fhorinek/SkyDrop/issues/75
https://github.com/fhorinek/SkyDrop/issues/77

### CODE REVIEW

**Comment by klaasvaak91** [comment]
Hi Bubeck, Im new to GitHub so im not sure if this is the good place to ask this question.

The skydrop arrived today and I started testing with home files, following the instructions in the "wiki". The distance to homepoints show correct behaviour but this is not the case for the direction. My compass is working like it should.
 If the homepoint is 1 km North of me it is possible for the homedirection to point SW, my compass does in this case point in direction of homepoint. If Im very close (30m or less) the homedirection arrow starts to show rotating behavioiur like aspected but if im further away the direction arrow isnt accurate. Above means that If im walking towars homepoint distance becomes smaller like it should, but according to direction arrow it should increase.

For homepoints very far away ( I tested for 70 and 900km) the distance is again correct but the direction arrow is always north, even if homepoints are south. 

Do you know if I could fix this and if more people have the same problem?

Many thanks, Sybrn

**Comment by bubeck** [comment]
Hi Sybrn

please use "issues" within GitHub to report questions like this. But no problem, we continue can continue here, even if the pull request is already closed.

What firmware version are you using? There has been a problem with compass and all other widgets. You can see this when turning the device on. Could be 4021 e.g.

Are you sure, that your compass is calibrated? Is it really working? Please keep in mind, that the direction is meant relative to SkyDrop and not to GPS movement. We consider the lower part of SkyDrop (with the cord) as south.

**Comment by klaasvaak91** [comment]
Hi Bubeck,

Allright thank you, will remember that for the next time.

It was shipped with firmware 4251, but I also tried downgrading to last two firmware versions but there the homearrow showed even more crazy behaviour. @4240 & 4245the homearrow would point for example to real SE, when skydroptop is pointing north when laying flat on table, and if skydroptop then is rotated to realSE the arrow would point  realSW. At FW 4251 it does show steady homedirection when skydrop is rotated while laying flat on table top but the direction itself is wrong. Compass is calibrated correctly and always shows North very close to true value  when it is rotated on table top. GPS also shows accurate positions. Thanks for your help! Im located in the north-east of the netherlands, if that may help. Is it a good Idea to try an even older firmware version? Or do you not encounter this problem with actual fw version?

As I understand the arrows.
 When compass is placed flat on table top the compass will point in direction of north. 
Grounddegree will point in direction of GPSmovement where up is north and down is south etc. 
Homearrow will point in direction where home is relative to skydrop, so if it points down while holding skydrop in natural position in your hand you should rotate 180 degrees and this is not the same as going south.
Many thanks for your help,
Sybren

**Comment by fhorinek** [comment]
I think that I might found a bug.
After imu rewrite I was checking the gps angle calculation with simulation software.
I think that I swap the latitude axis in the simulator. That might lead to wrong angle calculation.
Will check & fix if necesary

**Comment by klaasvaak91** [comment]
Hi Fhorinek,

If I place the skydrop on table and would swap the y component of homeArrow (similar transform like complex conjugate) it looks like it points in good direction for multiple homepoints.

**Comment by fhorinek** [comment]
Yes I did write the simulator with inverted y axis.
Stupid mistake: pixels are going down with rising numbers but the latitude up

**Pull request merged**
