### PR TITLE
Converted manual into markdown format.

### PR DESCRIPTION
**Pull request by bubeck**
This allows to improve the manual together with any new feature
in the same commit. So the manual is always up-to-date in regard to
the source code.

By using the attached Makefile, a PDF is generated to print
the manual. This is nearly identical to the original PDF.

Also, by using markdown, the manual can be viewed within GitHub
directly from markdown source.

You can see the generated PDF here:
https://github.com/bubeck/SkyDrop/blob/manual/skydrop/doc/manual/SkyDrop_user_manual_en.pdf

You can see the markdown (as a markdown preview) here: https://github.com/bubeck/SkyDrop/blob/manual/skydrop/doc/manual/SkyDrop_user_manual_en.md

The MD source is nearly 98% markdown and 2% HTML because of some special alignments to reach 100% identical PDF. If you are a little flexible in the layout, we can raise markdown to 100% and drop HTML. Still I think, that the manual is easy to understand and extend for anyone, even without markdown or HTML knowlegge.

### CODE REVIEW

**Comment by bubeck** [comment]
As a side remark: the markdown can also be put into the wiki area. This would allow anyone to edit the file and see the results immediately. This is good.

On the other hand we loose the coupling of different manual versions to the source code, which we have, if we make it part of the repository, instead of the wiki.

I propose to put a link inside the wiki to the PDF (and explain the way how to change the manual by cloning the repo, doing changes, and asking for pull).

What do you think?

**Comment by fhorinek** [comment]
I think it is enough to have the newest version on wiki. Online edit is much better think that version coupling. Since the software is nearly finished we do not need to have several version coupled with the code.

**Comment by bubeck** [comment]
Ok. Should I put it there?

**Comment by fhorinek** [comment]
yes please do

**Comment by bubeck** [comment]
Done. The online version is available under https://github.com/fhorinek/SkyDrop/wiki/Manual-of-SkyDrop
but needs the images from this pull request. So please merge.

**Comment by bubeck** [comment]
Fero, have you tried

`cd skydrop/doc/manual ; make
`

Is it working? Is the resulting PDF good enough to replace the original word document? Does it therefore make sende to improve the wiki page to describe _all_ existing functionalities?

**Pull request merged**
